export const surpriseMePrompts = [
  "an armchair in the shape of an avocado",
  "a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers",
  "teddy bears shopping for groceries in Japan, ukiyo-e",
  "an oil painting by Matisse of a humanoid robot playing chess",
  "panda mad scientist mixing sparkling chemicals, digital art",
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  "3D render of a cute tropical fish in an aquarium on a dark blue background, digital art",
  "an astronaut lounging in a tropical resort in space, vaporwave",
  "an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background",
  "a stained glass window depicting a hamburger and french fries",
  "a pencil and watercolor drawing of a bright city in the future with flying cars",
  "a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art",
  "a fortune-telling shiba inu reading your fate in a giant hamburger, digital art",
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  "an oil pastel drawing of an annoyed cat in a spaceship",
  "a painting of a fox in the style of Starry Night",
  "a bowl of soup that looks like a monster, knitted out of wool",
  "A plush toy robot sitting against a yellow wall",
  "A synthwave style sunset above the reflecting water of the sea, digital art",
  "Two futuristic towers with a skybridge covered in lush foliage, digital art",
  "A 3D render of a rainbow colored hot air balloon flying above a reflective lake",
  "A comic book cover of a superhero wearing headphones",
  "A centered explosion of colorful powder on a black background",
  "A photo of a Samoyed dog with its tongue out hugging a white Siamese cat",
  "A photo of a white fur monster standing in a purple room",
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  "A Samurai riding a Horse on Mars, lomography.",
  "A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography",
  "A realistic photograph of a young woman with blue eyes and blonde hair",
  "A man standing in front of a stargate to another dimension",
  "Spongebob Squarepants in the Blair Witch Project",
  "A velociraptor working at a hotdog stand, lomography",
  "A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens",
  "A BBQ that is alive, in the style of a Pixar animated movie",
  "A futuristic cyborg dance club, neon lights",
  "The long-lost Star Wars 1990 Japanese Anime",
  "A hamburger in the shape of a Rubik’s cube, professional food photography",
  "A Synthwave Hedgehog, Blade Runner Cyberpunk",
  "An astronaut encountering an alien life form on a distant planet, photography",
  "A Dinosaur exploring Cape Town, photography",
  "A Man falling in Love with his Computer, digital art",
  "A photograph of a cyborg exploring Tokyo at night, lomography",
  "Dracula walking down the street of New York City in the 1920s, black and white photography",
  "Synthwave aeroplane",
  "A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm",
  "A Space Shuttle flying above Cape Town, digital art",
];

export const surpriseMePromptsBr = [
  "uma poltrona em formato de abacate",
  "uma pintura surrealista de Salvador Dalí de um gato jogando xadrez",
  "ursos de pelúcia fazendo compras em um supermercado no Japão, ukiyo-e",
  "uma pintura a óleo de Matisse de um robô humanoid jogando xadrez",
  "cientista panda misturando produtos químicos brilhantes, arte digital",
  "uma fotografia macro de dois ratos no Havaí, cada um vestindo pequenos trajes de banho e carregando pranchas de surf, arte digital",
  "renderização 3D de um peixe tropical fofo em um aquário em um fundo azul escuro, arte digital",
  "um astronauta relaxando em um resort tropical no espaço, vaporwave",
  "um retrato a óleo de um capivara usando trajes medievais reais e uma coroa ornamental em um fundo escuro",
  "um vitral representando um hambúrguer e batatas fritas",
  "um desenho a lápis e aquarela de uma cidade brilhante do futuro com carros voadores",
  "uma área de lounge interna com luz do sol com uma piscina com água cristalina e outra piscina com água rosa translúcida, ao lado de uma grande janela, arte digital",
  "um shiba inu lendo sua sorte em um hambúrguer gigante, arte digital",
  '"uma lontra marinha com brinco de pérola" por Johannes Vermeer',
  "um desenho a óleo pastel de um gato irritado em uma nave espacial",
  'uma pintura de uma raposa no estilo de "Noite Estrelada"',
  "uma tigela de sopa que parece um monstro, feita de lã",
  "um robô de pelúcia sentado contra uma parede amarela",
  "um pôr do sol no estilo synthwave acima da água reflexiva do mar, arte digital",
  "duas torres futuristas com uma ponte suspensa coberta por folhagem exuberante, arte digital",
  "uma renderização 3D de um balão de ar quente colorido do arco-íris voando acima de um lago reflexivo",
  "uma capa de quadrinhos de um super-herói usando fones de ouvido",
  "uma explosão centralizada de pó colorido em um fundo preto",
  "uma foto de um cachorro Samoiedo com a língua de fora abraçando um gato siamês branco",
  "uma foto de um monstro de pele branca em uma sala roxa",
  'uma foto da escultura "David", de Michelangelo, usando fones de ouvido e mixando música',
  "um samurai montado em um cavalo em Marte, lomografia",
  "um Cadillac moderno e elegante dirigindo pela autoestrada Gardiner com o centro de Toronto ao fundo, com um efeito de lente, fotografia de 50mm",
  "uma fotografia realista de uma jovem com olhos azuis e cabelo loiro",
  "um homem parado na frente de uma porta estelar para outra dimensão",
  "SpongeBob SquarePants no Projeto Blair Witch",
  "Um velociraptor trabalhando em um carrinho de cachorro-quente, em estilo lomografia",
  "Um homem caminhando pelas movimentadas ruas de Kowloon à noite, iluminadas por muitas luminosas lojas de neon, lente 50mm",
  "Um churrasco que está vivo, no estilo de um filme animado da Pixar",
  "Um clube de dança ciborgue futurista, luzes neon",
  "O perdido Star Wars 1990 Japanese Anime",
  "Um hambúrguer em forma de cubo de Rubik, fotografia profissional de comida",
  "Um ouriço Synthwave, Blade Runner Cyberpunk",
  "Um astronauta encontrando uma forma de vida alienígena em um planeta distante, fotografia",
  "Um dinossauro explorando Cape Town, fotografia",
  "Um homem se apaixonando por seu computador, arte digital",
  "Uma fotografia de um ciborgue explorando Tóquio à noite, em estilo lomografia",
  "Dracula caminhando pelas ruas de Nova York na década de 1920, fotografia em preto e branco",
  "Aeroplano Synthwave",
  "Um homem caminha pelas ruas chuvosas de Tóquio, com luminosos neon brilhantes, lente 50mm",
  "Um ônibus espacial voando acima de Cape Town, arte digital",
];
